
#server:
#  port: 8080

spring:
  application:
    name: comit-spring
    

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework: INFO

# Thymeleaf Configuration (Optional)
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
